//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 2.0.5.0
// 
namespace GHDoctor.ModelServicesReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://tempuri.org/")]
    public partial class Category : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int CodeField;
        
        private string ShortDescriptionField;
        
        private string LongDescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ShortDescription {
            get {
                return this.ShortDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortDescriptionField, value) != true)) {
                    this.ShortDescriptionField = value;
                    this.RaisePropertyChanged("ShortDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LongDescription {
            get {
                return this.LongDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.LongDescriptionField, value) != true)) {
                    this.LongDescriptionField = value;
                    this.RaisePropertyChanged("LongDescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommonQuery", Namespace="http://tempuri.org/")]
    public partial class CommonQuery : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long CodeField;
        
        private int CategoryCodeField;
        
        private string ShortDescriptionField;
        
        private string DescriptionField;
        
        private string SearchStringField;
        
        private GHDoctor.ModelServicesReference.Category CategoryField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int CategoryCode {
            get {
                return this.CategoryCodeField;
            }
            set {
                if ((this.CategoryCodeField.Equals(value) != true)) {
                    this.CategoryCodeField = value;
                    this.RaisePropertyChanged("CategoryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ShortDescription {
            get {
                return this.ShortDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortDescriptionField, value) != true)) {
                    this.ShortDescriptionField = value;
                    this.RaisePropertyChanged("ShortDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SearchString {
            get {
                return this.SearchStringField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchStringField, value) != true)) {
                    this.SearchStringField = value;
                    this.RaisePropertyChanged("SearchString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public GHDoctor.ModelServicesReference.Category Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ModelServicesReference.ModelServicesSoap")]
    public interface ModelServicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetAllCategories", ReplyAction="*")]
        System.IAsyncResult BeginGetAllCategories(GHDoctor.ModelServicesReference.GetAllCategoriesRequest request, System.AsyncCallback callback, object asyncState);
        
        GHDoctor.ModelServicesReference.GetAllCategoriesResponse EndGetAllCategories(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetCommonQueries", ReplyAction="*")]
        System.IAsyncResult BeginGetCommonQueries(GHDoctor.ModelServicesReference.GetCommonQueriesRequest request, System.AsyncCallback callback, object asyncState);
        
        GHDoctor.ModelServicesReference.GetCommonQueriesResponse EndGetCommonQueries(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCategoriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCategories", Namespace="http://tempuri.org/", Order=0)]
        public GHDoctor.ModelServicesReference.GetAllCategoriesRequestBody Body;
        
        public GetAllCategoriesRequest() {
        }
        
        public GetAllCategoriesRequest(GHDoctor.ModelServicesReference.GetAllCategoriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllCategoriesRequestBody {
        
        public GetAllCategoriesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCategoriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCategoriesResponse", Namespace="http://tempuri.org/", Order=0)]
        public GHDoctor.ModelServicesReference.GetAllCategoriesResponseBody Body;
        
        public GetAllCategoriesResponse() {
        }
        
        public GetAllCategoriesResponse(GHDoctor.ModelServicesReference.GetAllCategoriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllCategoriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<GHDoctor.ModelServicesReference.Category> GetAllCategoriesResult;
        
        public GetAllCategoriesResponseBody() {
        }
        
        public GetAllCategoriesResponseBody(System.Collections.ObjectModel.ObservableCollection<GHDoctor.ModelServicesReference.Category> GetAllCategoriesResult) {
            this.GetAllCategoriesResult = GetAllCategoriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCommonQueriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCommonQueries", Namespace="http://tempuri.org/", Order=0)]
        public GHDoctor.ModelServicesReference.GetCommonQueriesRequestBody Body;
        
        public GetCommonQueriesRequest() {
        }
        
        public GetCommonQueriesRequest(GHDoctor.ModelServicesReference.GetCommonQueriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCommonQueriesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int categoryCode;
        
        public GetCommonQueriesRequestBody() {
        }
        
        public GetCommonQueriesRequestBody(int categoryCode) {
            this.categoryCode = categoryCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCommonQueriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCommonQueriesResponse", Namespace="http://tempuri.org/", Order=0)]
        public GHDoctor.ModelServicesReference.GetCommonQueriesResponseBody Body;
        
        public GetCommonQueriesResponse() {
        }
        
        public GetCommonQueriesResponse(GHDoctor.ModelServicesReference.GetCommonQueriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCommonQueriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<GHDoctor.ModelServicesReference.CommonQuery> GetCommonQueriesResult;
        
        public GetCommonQueriesResponseBody() {
        }
        
        public GetCommonQueriesResponseBody(System.Collections.ObjectModel.ObservableCollection<GHDoctor.ModelServicesReference.CommonQuery> GetCommonQueriesResult) {
            this.GetCommonQueriesResult = GetCommonQueriesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ModelServicesSoapChannel : GHDoctor.ModelServicesReference.ModelServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetAllCategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllCategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<GHDoctor.ModelServicesReference.Category> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<GHDoctor.ModelServicesReference.Category>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetCommonQueriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCommonQueriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<GHDoctor.ModelServicesReference.CommonQuery> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<GHDoctor.ModelServicesReference.CommonQuery>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ModelServicesSoapClient : System.ServiceModel.ClientBase<GHDoctor.ModelServicesReference.ModelServicesSoap>, GHDoctor.ModelServicesReference.ModelServicesSoap {
        
        private BeginOperationDelegate onBeginGetAllCategoriesDelegate;
        
        private EndOperationDelegate onEndGetAllCategoriesDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllCategoriesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCommonQueriesDelegate;
        
        private EndOperationDelegate onEndGetCommonQueriesDelegate;
        
        private System.Threading.SendOrPostCallback onGetCommonQueriesCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ModelServicesSoapClient() {
        }
        
        public ModelServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ModelServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModelServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModelServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetAllCategoriesCompletedEventArgs> GetAllCategoriesCompleted;
        
        public event System.EventHandler<GetCommonQueriesCompletedEventArgs> GetCommonQueriesCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GHDoctor.ModelServicesReference.ModelServicesSoap.BeginGetAllCategories(GHDoctor.ModelServicesReference.GetAllCategoriesRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllCategories(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetAllCategories(System.AsyncCallback callback, object asyncState) {
            GHDoctor.ModelServicesReference.GetAllCategoriesRequest inValue = new GHDoctor.ModelServicesReference.GetAllCategoriesRequest();
            inValue.Body = new GHDoctor.ModelServicesReference.GetAllCategoriesRequestBody();
            return ((GHDoctor.ModelServicesReference.ModelServicesSoap)(this)).BeginGetAllCategories(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GHDoctor.ModelServicesReference.GetAllCategoriesResponse GHDoctor.ModelServicesReference.ModelServicesSoap.EndGetAllCategories(System.IAsyncResult result) {
            return base.Channel.EndGetAllCategories(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.Collections.ObjectModel.ObservableCollection<GHDoctor.ModelServicesReference.Category> EndGetAllCategories(System.IAsyncResult result) {
            GHDoctor.ModelServicesReference.GetAllCategoriesResponse retVal = ((GHDoctor.ModelServicesReference.ModelServicesSoap)(this)).EndGetAllCategories(result);
            return retVal.Body.GetAllCategoriesResult;
        }
        
        private System.IAsyncResult OnBeginGetAllCategories(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetAllCategories(callback, asyncState);
        }
        
        private object[] OnEndGetAllCategories(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<GHDoctor.ModelServicesReference.Category> retVal = this.EndGetAllCategories(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllCategoriesCompleted(object state) {
            if ((this.GetAllCategoriesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllCategoriesCompleted(this, new GetAllCategoriesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllCategoriesAsync() {
            this.GetAllCategoriesAsync(null);
        }
        
        public void GetAllCategoriesAsync(object userState) {
            if ((this.onBeginGetAllCategoriesDelegate == null)) {
                this.onBeginGetAllCategoriesDelegate = new BeginOperationDelegate(this.OnBeginGetAllCategories);
            }
            if ((this.onEndGetAllCategoriesDelegate == null)) {
                this.onEndGetAllCategoriesDelegate = new EndOperationDelegate(this.OnEndGetAllCategories);
            }
            if ((this.onGetAllCategoriesCompletedDelegate == null)) {
                this.onGetAllCategoriesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllCategoriesCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllCategoriesDelegate, null, this.onEndGetAllCategoriesDelegate, this.onGetAllCategoriesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GHDoctor.ModelServicesReference.ModelServicesSoap.BeginGetCommonQueries(GHDoctor.ModelServicesReference.GetCommonQueriesRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCommonQueries(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetCommonQueries(int categoryCode, System.AsyncCallback callback, object asyncState) {
            GHDoctor.ModelServicesReference.GetCommonQueriesRequest inValue = new GHDoctor.ModelServicesReference.GetCommonQueriesRequest();
            inValue.Body = new GHDoctor.ModelServicesReference.GetCommonQueriesRequestBody();
            inValue.Body.categoryCode = categoryCode;
            return ((GHDoctor.ModelServicesReference.ModelServicesSoap)(this)).BeginGetCommonQueries(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GHDoctor.ModelServicesReference.GetCommonQueriesResponse GHDoctor.ModelServicesReference.ModelServicesSoap.EndGetCommonQueries(System.IAsyncResult result) {
            return base.Channel.EndGetCommonQueries(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.Collections.ObjectModel.ObservableCollection<GHDoctor.ModelServicesReference.CommonQuery> EndGetCommonQueries(System.IAsyncResult result) {
            GHDoctor.ModelServicesReference.GetCommonQueriesResponse retVal = ((GHDoctor.ModelServicesReference.ModelServicesSoap)(this)).EndGetCommonQueries(result);
            return retVal.Body.GetCommonQueriesResult;
        }
        
        private System.IAsyncResult OnBeginGetCommonQueries(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int categoryCode = ((int)(inValues[0]));
            return this.BeginGetCommonQueries(categoryCode, callback, asyncState);
        }
        
        private object[] OnEndGetCommonQueries(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<GHDoctor.ModelServicesReference.CommonQuery> retVal = this.EndGetCommonQueries(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCommonQueriesCompleted(object state) {
            if ((this.GetCommonQueriesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCommonQueriesCompleted(this, new GetCommonQueriesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCommonQueriesAsync(int categoryCode) {
            this.GetCommonQueriesAsync(categoryCode, null);
        }
        
        public void GetCommonQueriesAsync(int categoryCode, object userState) {
            if ((this.onBeginGetCommonQueriesDelegate == null)) {
                this.onBeginGetCommonQueriesDelegate = new BeginOperationDelegate(this.OnBeginGetCommonQueries);
            }
            if ((this.onEndGetCommonQueriesDelegate == null)) {
                this.onEndGetCommonQueriesDelegate = new EndOperationDelegate(this.OnEndGetCommonQueries);
            }
            if ((this.onGetCommonQueriesCompletedDelegate == null)) {
                this.onGetCommonQueriesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCommonQueriesCompleted);
            }
            base.InvokeAsync(this.onBeginGetCommonQueriesDelegate, new object[] {
                        categoryCode}, this.onEndGetCommonQueriesDelegate, this.onGetCommonQueriesCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override GHDoctor.ModelServicesReference.ModelServicesSoap CreateChannel() {
            return new ModelServicesSoapClientChannel(this);
        }
        
        private class ModelServicesSoapClientChannel : ChannelBase<GHDoctor.ModelServicesReference.ModelServicesSoap>, GHDoctor.ModelServicesReference.ModelServicesSoap {
            
            public ModelServicesSoapClientChannel(System.ServiceModel.ClientBase<GHDoctor.ModelServicesReference.ModelServicesSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetAllCategories(GHDoctor.ModelServicesReference.GetAllCategoriesRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetAllCategories", _args, callback, asyncState);
                return _result;
            }
            
            public GHDoctor.ModelServicesReference.GetAllCategoriesResponse EndGetAllCategories(System.IAsyncResult result) {
                object[] _args = new object[0];
                GHDoctor.ModelServicesReference.GetAllCategoriesResponse _result = ((GHDoctor.ModelServicesReference.GetAllCategoriesResponse)(base.EndInvoke("GetAllCategories", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetCommonQueries(GHDoctor.ModelServicesReference.GetCommonQueriesRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetCommonQueries", _args, callback, asyncState);
                return _result;
            }
            
            public GHDoctor.ModelServicesReference.GetCommonQueriesResponse EndGetCommonQueries(System.IAsyncResult result) {
                object[] _args = new object[0];
                GHDoctor.ModelServicesReference.GetCommonQueriesResponse _result = ((GHDoctor.ModelServicesReference.GetCommonQueriesResponse)(base.EndInvoke("GetCommonQueries", _args, result)));
                return _result;
            }
        }
    }
}
