USE [master]
GO
/****** Object:  Database [GHDoctor]    Script Date: 11/16/2009 01:03:24 ******/
CREATE DATABASE [GHDoctor] ON  PRIMARY 
( NAME = N'GHDoctor', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\GHDoctor.mdf' , SIZE = 2240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'GHDoctor_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\GHDoctor_log.LDF' , SIZE = 560KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 COLLATE Modern_Spanish_CI_AS
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'GHDoctor', @new_cmptlevel=90
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GHDoctor].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [GHDoctor] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GHDoctor] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GHDoctor] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GHDoctor] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GHDoctor] SET ARITHABORT OFF 
GO
ALTER DATABASE [GHDoctor] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [GHDoctor] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [GHDoctor] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GHDoctor] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GHDoctor] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GHDoctor] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GHDoctor] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GHDoctor] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GHDoctor] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GHDoctor] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GHDoctor] SET  ENABLE_BROKER 
GO
ALTER DATABASE [GHDoctor] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [GHDoctor] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GHDoctor] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [GHDoctor] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [GHDoctor] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GHDoctor] SET  READ_WRITE 
GO
ALTER DATABASE [GHDoctor] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [GHDoctor] SET  MULTI_USER 
GO
ALTER DATABASE [GHDoctor] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GHDoctor] SET DB_CHAINING OFF 