insert into CATEGORY (SHORT_DESCRIPTION,LONG_DESCRIPTION) values ('Advisories and Vulnerabilities','These searches locate vulnerable servers. These searches are often generated from various security advisory posts, and in many cases are product or version-specific.');
insert into CATEGORY (SHORT_DESCRIPTION,LONG_DESCRIPTION) values ('Error Messages','Really retarded error messages that say WAY too much!');
insert into CATEGORY (SHORT_DESCRIPTION,LONG_DESCRIPTION) values ('Files containing juicy info','No usernames or passwords, but interesting stuff none the less.');
insert into CATEGORY (SHORT_DESCRIPTION,LONG_DESCRIPTION) values ('Files containing passwords','PASSWORDS, for the LOVE OF GOD!!! Google found PASSWORDS!');
insert into CATEGORY (SHORT_DESCRIPTION,LONG_DESCRIPTION) values ('Files containing usernames','These files contain usernames, but no passwords… Still, google finding usernames on a web site.');
insert into CATEGORY (SHORT_DESCRIPTION,LONG_DESCRIPTION) values ('Footholds','Examples of queries that can help a hacker gain a foothold into a web server.');
insert into CATEGORY (SHORT_DESCRIPTION,LONG_DESCRIPTION) values ('Pages containing login portals','These are login pages for various services. Consider them the front door of a website’s more sensitive functions.');
insert into CATEGORY (SHORT_DESCRIPTION,LONG_DESCRIPTION) values ('Pages containing network or vulnerability data','These pages contain such things as firewall logs, honeypot logs, network information, IDS logs… all sorts of fun stuff!');
insert into CATEGORY (SHORT_DESCRIPTION,LONG_DESCRIPTION) values ('sensitive Directories','Google’s collection of web sites sharing sensitive directories. The files contained in here will vary from sesitive to uber-secret!');
insert into CATEGORY (SHORT_DESCRIPTION,LONG_DESCRIPTION) values ('sensitive Online Shopping Info','Examples of queries that can reveal online shopping info like customer data, suppliers, orders, creditcard numbers, credit card info, etc.');
insert into CATEGORY (SHORT_DESCRIPTION,LONG_DESCRIPTION) values ('Various Online Devices','This category contains things like printers, video cameras, and all sorts of cool things found on the web with Google.');
insert into CATEGORY (SHORT_DESCRIPTION,LONG_DESCRIPTION) values ('Vulnerable Files','HUNDREDS of vulnerable files that Google can find on websites.');
insert into CATEGORY (SHORT_DESCRIPTION,LONG_DESCRIPTION) values ('Vulnerable Servers','These searches reveal servers with specific vulnerabilities. These are found in a different way than the searches found in the “Vulnerable Files” section.');
insert into CATEGORY (SHORT_DESCRIPTION,LONG_DESCRIPTION) values ('Web Server Detection','These links demonstrate Google’s awesome ability to profile web servers.');
GO